"""Which days were actually collected, and which are holes.

The database is the only record of what was collected -- the log rotates, the
scheduled task lies, and a run that died mid-walk still leaves a log tail that
looks like success. So this asks Supabase for an exact row count per day.

A GAP is a day with zero rows: nobody looked, so nothing can be inferred about
any listing on it. Those days are what the survival model must treat as
interval-censored -- a listing that vanishes across a gap did not necessarily
vanish on the first missing day.

A THIN day is a day with rows but fewer than SCRAPE_MIN_EXPECTED. It is NOT a
gap: the harvest is partial, so an absence on a thin day is weak evidence rather
than no evidence. Reported separately, and deliberately not merged into the gap
list -- collapsing the two would silently discard real observations.

Row counts before 2026-08-09 sit near 2,000 because the crawl was smaller then,
not because those days are thin. The threshold postdates them; judge them by
eye, not by the flag.

Today is excluded by default -- the collector may still be walking, and a
half-finished day is not a thin day.

    python collection_gaps.py              # table to stdout
    python collection_gaps.py --markdown   # regenerate docs/collection-gaps.md
    python collection_gaps.py --today      # include today (mid-run counts)
"""
from __future__ import annotations

import sys
from datetime import date, timedelta

from scraper.store import MIN_COMPLETE, day_row_count

START = date(2026, 7, 19)  # data collection day 0
DOC = "docs/collection-gaps.md"


def audit(through: date) -> list[tuple[date, int]]:
    days, d = [], START
    while d <= through:
        days.append((d, day_row_count(d)))
        d += timedelta(days=1)
    return days


def runs(days: list[tuple[date, int]]) -> list[tuple[date, date]]:
    """Collapse zero-row days into consecutive [first, last] intervals."""
    out: list[list[date]] = []
    for d, n in days:
        if n:
            continue
        if out and d - out[-1][1] == timedelta(days=1):
            out[-1][1] = d
        else:
            out.append([d, d])
    return [(a, b) for a, b in out]


def markdown(days: list[tuple[date, int]]) -> str:
    gaps = runs(days)
    thin = [(d, n) for d, n in days if 0 < n < MIN_COMPLETE and d >= date(2026, 8, 9)]
    missing = sum(1 for _, n in days if not n)

    lines = [
        "# Collection gaps",
        "",
        f"Generated by `collection_gaps.py` on {date.today().isoformat()}. "
        "Do not hand-edit -- regenerate.",
        "",
        f"Collection start {START.isoformat()}, audited through "
        f"{days[-1][0].isoformat()}: {len(days)} calendar days, "
        f"{len(days) - missing} collected, {missing} missing.",
        "",
        "## Censoring intervals (zero rows -- nobody looked)",
        "",
        "| From | To | Days |",
        "| --- | --- | --- |",
    ]
    for a, b in gaps:
        lines.append(f"| {a.isoformat()} | {b.isoformat()} | {(b - a).days + 1} |")

    lines += [
        "",
        "A listing last seen before one of these intervals and absent after it "
        "exited somewhere inside the interval. Its exit day is unknown to within "
        "the interval width, which is exactly interval censoring -- not a right-"
        "censored survivor, and not an exit on the first missing day.",
        "",
        f"## Thin days (rows, but under {MIN_COMPLETE:,})",
        "",
        "Partial harvests. Absence here is weak evidence, not no evidence -- these "
        "are NOT censoring intervals.",
        "",
        "| Day | Rows |",
        "| --- | --- |",
    ]
    for d, n in thin:
        lines.append(f"| {d.isoformat()} | {n:,} |")

    lines += [
        "",
        "## Full daily counts",
        "",
        "| Day | Rows |",
        "| --- | --- |",
    ]
    for d, n in days:
        lines.append(f"| {d.isoformat()} | {n:,} |")
    return "\n".join(lines) + "\n"


def _test() -> None:
    """Self-check on synthetic counts, no network."""
    d = date(2026, 1, 1)
    days = [
        (d, 100), (d + timedelta(1), 0), (d + timedelta(2), 0),
        (d + timedelta(3), 100), (d + timedelta(4), 0),
    ]
    assert runs(days) == [
        (d + timedelta(1), d + timedelta(2)),
        (d + timedelta(4), d + timedelta(4)),
    ]
    assert runs([(d, 100)]) == []
    assert runs([(d, 0)]) == [(d, d)]
    print("ok")


def main() -> None:
    if "--test" in sys.argv:
        return _test()
    through = date.today() if "--today" in sys.argv else date.today() - timedelta(days=1)
    days = audit(through)
    if "--markdown" in sys.argv:
        open(DOC, "w", encoding="utf-8").write(markdown(days))
        print(f"wrote {DOC}")
        return
    for d, n in days:
        flag = "MISSING" if not n else ("thin" if n < MIN_COMPLETE else "")
        print(f"{d}  {n:6d}  {flag}")


if __name__ == "__main__":
    main()
